__title__ = "laser cut box"
__author__ = "Greg Harley"
__version__ = "01.00"
__date__ = "12/31/20"

__Comment__ = "This macro creates a sketch of a laser cut box which can then be save to a DXF file."

from PySide import QtCore, QtGui
from FreeCAD import Gui
import Part, Sketcher

App = FreeCAD

START = 1
END = 2
ORIGIN = -1


class Box:
    def __init__(self):
        if not App.ActiveDocument:
            App.newDocument()

        self.dialog = None
        self.worksheet = None
        self.box_type = 0

        self.init_dialog()

        self.dialog.show()
        self.dialog.exec_()

    def init_dialog(self):
        self.dialog = Gui.PySideUic.loadUi("C:/Users/gharley/AppData/Roaming/FreeCAD/Macro/Macro_LaserCutBox.ui")
        self.dialog.setWindowTitle("Laser cut box")

        QtCore.QObject.connect(self.dialog.buttonBox, QtCore.SIGNAL("accepted()"), self.init_sheet)

    def init_sheet(self):
        self.worksheet = App.ActiveDocument.addObject("Spreadsheet::Sheet", "Parameters")
        set_cell = self.worksheet.set
        self.worksheet.setColumnWidth('A', 150)

        index = 0
        for obj in self.dialog.findChildren(QtGui.QLabel):
            index += 1
            column_a = 'A' + str(index)
            column_b = 'B' + str(index)

            alias = obj.buddy()
            if not (alias is None):
                if isinstance(alias, QtGui.QComboBox):
                    self.box_type = alias.currentIndex
                    index -= 1
                else:
                    set_cell(column_a, obj.text())
                    set_cell(column_b, alias.text())
                    self.worksheet.setAlias(column_b, alias.objectName())
            else:
                self.worksheet.setStyle(column_a, 'bold')
                self.worksheet.setAlignment(column_a, 'center|vcenter')
                self.worksheet.mergeCells(column_a + ':' + column_b)
                set_cell(column_a, obj.text())

        App.ActiveDocument.recompute(None, True, True)

        self.build_long_side()

    def build_long_side(self):
        sheet = self.worksheet
        sheet_prefix = "<<" + App.ActiveDocument.ActiveObject.Name + ">>."

        width = sheet.get(sheet.getCellFromAlias("width"))
        height = sheet.get(sheet.getCellFromAlias("height"))

        lower_left = App.Vector(0, 0, 0)
        upper_left = App.Vector(0, height, 0)
        lower_right = App.Vector(width, 0, 0)
        upper_right = App.Vector(width, height, 0)

        sketch = App.ActiveDocument.addObject("Sketcher::SketchObject", "Sketch")

        top = sketch.addGeometry(Part.LineSegment(upper_left, upper_right), False)
        right = sketch.addGeometry(Part.LineSegment(upper_right, lower_right), False)
        bottom = sketch.addGeometry(Part.LineSegment(lower_right, lower_left), False)
        left = sketch.addGeometry(Part.LineSegment(lower_left, upper_left), False)

        constraint = sketch.addConstraint(Sketcher.Constraint('DistanceX', top, width))
        sketch.setExpression("Constraints[" + str(constraint) + "]", sheet_prefix + "width")

        constraint = sketch.addConstraint(Sketcher.Constraint('DistanceY', left, height))
        sketch.setExpression("Constraints[" + str(constraint) + "]", sheet_prefix + "height")

        sketch.addConstraint(Sketcher.Constraint('Horizontal', top))
        sketch.addConstraint(Sketcher.Constraint('Horizontal', bottom))
        sketch.addConstraint(Sketcher.Constraint('Vertical', left))
        sketch.addConstraint(Sketcher.Constraint('Vertical', right))

        sketch.addConstraint(Sketcher.Constraint('Coincident', top, END, right, START))
        sketch.addConstraint(Sketcher.Constraint('Coincident', right, END, bottom, START))
        sketch.addConstraint(Sketcher.Constraint('Coincident', bottom, END, left, START))
        sketch.addConstraint(Sketcher.Constraint('Coincident', left, END, top, START))

        # sketch.delGeometry(bottom)
        sketch.addConstraint(Sketcher.Constraint('Symmetric', top, START, bottom, START, ORIGIN, START))

        App.ActiveDocument.recompute(None, True, True)
        Gui.ActiveDocument.ActiveView.fitAll()


Box()
